### ISSUE TITLE
MD2023 breaks extension StringUtils has moved....

### ISSUE THREAD

**Issue by yogi1967** [stant/mdcsvimporter2015#14]
In MD2023 the class/method com.moneydance.util.StringUtils was removed.
The correct/new class/method reference is: com.infinitekind.til.StringUtils

Extension is failing:
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/moneydance/util/StringUtils
    at com.moneydance.modules.features.mdcsvimporter.formats.CustomReader.parseNext(CustomReader.java:564)
    at com.moneydance.modules.features.mdcsvimporter.TransactionReader.parse(TransactionReader.java:382)
    at com.moneydance.modules.features.mdcsvimporter.ImportDialog.processActionPerformed(ImportDialog.java:491)
    at com.moneydance.modules.features.mdcsvimporter.ImportDialog.btnProcessActionPerformed(ImportDialog.java:993)
    at com.moneydance.modules.features.mdcsvimporter.ImportDialog.access$400(ImportDialog.java:46)
    at com.moneydance.modules.features.mdcsvimporter.ImportDialog$5.actionPerformed(ImportDialog.java:662)

Please can you fix? Thanks

**Comment by Kevin-N749** [comment]
Another fix request please.
Thanks

**Comment by yogi1967** [comment]
@Kevin-N749 - I have decided to fix this extension myself. Contact me if you want a copy..

**Comment by yogi1967** [comment]
Hi Stan, I have forked and fixed the code. Pull request is waiting... I was wondering whether you wanted to put this code into the MD Open Source repo...? Depends if you want to actively maintain this going forward? Just a thought. Shout if any questions? SCB

**Comment by yogi1967** [comment]
.. and/or.... if you feel it appropriate, by all means grant me permissions to make changes directly in your repo? SCB
